from enum import Enum
import os
import vapoursynth as vs
core = vs.core

imagepath: str = os.path.join(os.path.dirname(os.path.realpath(__file__)), "images")

class Base(Enum):
    def __str__(self):
        directory = self.__class__.__name__
        return os.path.join(imagepath, directory, self.value)

    def load(self) -> vs.VideoNode:
        try:
            return core.bs.VideoSource(self)
        except:
            return core.imwri.Read(self)
        else:
            raise Exception(f"failed to index {self}")

class Data:
    class Julia(Base, Enum):
        """Julia dataset"""

        airplaneF16 = "airplaneF16.tiff"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        autumn_leaves = "autumn_leaves.png"
        """{'Format': 'RGB48', 'Width': 140, 'Height': 105, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        barbara_color = "barbara_color.png"
        """{'Format': 'RGB24', 'Width': 720, 'Height': 576, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        barbara_gray_512 = "barbara_gray_512.bmp"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bark_512 = "bark_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bark_he_512 = "bark_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        beach_sand_512 = "beach_sand_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        beach_sand_he_512 = "beach_sand_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        blobs = "blobs.gif"
        """{'Format': 'RGB24', 'Width': 256, 'Height': 254, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        brick_wall_512 = "brick_wall_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        brick_wall_he_512 = "brick_wall_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        calf_leather_512 = "calf_leather_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        calf_leather_he_512 = "calf_leather_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        cameraman = "cameraman.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        chelsea = "chelsea.png"
        """{'Format': 'RGB24', 'Width': 451, 'Height': 300, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        coffee = "coffee.png"
        """{'Format': 'RGB24', 'Width': 600, 'Height': 400, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        earth_apollo17 = "earth_apollo17.jpg"
        """{'Format': 'YUV444P8', 'Width': 3000, 'Height': 3002, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fabio_color_256 = "fabio_color_256.png"
        """{'Format': 'RGB24', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fabio_color_512 = "fabio_color_512.png"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fabio_gray_256 = "fabio_gray_256.png"
        """{'Format': 'Gray8', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fabio_gray_512 = "fabio_gray_512.png"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        grass_512 = "grass_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        grass_he_512 = "grass_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        hela_cells = "hela-cells.tif"
        """{'Format': 'RGB48', 'Width': 672, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        herringbone_weave_512 = "herringbone_weave_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        herringbone_weave_he_512 = "herringbone_weave_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        house = "house.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        jetplane = "jetplane.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lake_color = "lake_color.tif"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        lake_gray = "lake_gray.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lena_color_256 = "lena_color_256.tif"
        """{'Format': 'RGB24', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lena_color_512 = "lena_color_512.tif"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lena_gray_16bit = "lena_gray_16bit.png"
        """{'Format': 'Gray16', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lena_gray_256 = "lena_gray_256.tif"
        """{'Format': 'Gray8', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lena_gray_512 = "lena_gray_512.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lighthouse = "lighthouse.png"
        """{'Format': 'RGB24', 'Width': 768, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        lilly = "lilly.jpg"
        """{'Format': 'YUV420P8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        livingroom = "livingroom.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        m51 = "m51.tif"
        """{'Format': 'Gray16', 'Width': 320, 'Height': 510, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        mandrill = "mandrill.tiff"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        mandril_color = "mandril_color.tif"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        mandril_gray = "mandril_gray.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        monarch_color = "monarch_color.png"
        """{'Format': 'RGB24', 'Width': 768, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        monarch_color_256 = "monarch_color_256.png"
        """{'Format': 'RGB24', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        moonsurface = "moonsurface.tiff"
        """{'Format': 'Gray8', 'Width': 256, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        morphology_test_512 = "morphology_test_512.tiff"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        mountainstream = "mountainstream.png"
        """{'Format': 'RGB24', 'Width': 768, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        mri_stack = "mri-stack.tif"
        """{'Format': 'Gray8', 'Width': 186, 'Height': 226, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        multi_channel_time_series_ome = "multi-channel-time-series.ome.tif"
        """{'Format': 'Gray8', 'Width': 439, 'Height': 167, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        peppers_color = "peppers_color.tif"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        peppers_gray = "peppers_gray.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pigskin_512 = "pigskin_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pigskin_he_512 = "pigskin_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pirate = "pirate.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        plastic_bubbles_512 = "plastic_bubbles_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        plastic_bubbles_he_512 = "plastic_bubbles_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        raffia_512 = "raffia_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        raffia_he_512 = "raffia_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        resolution_test_1920 = "resolution_test_1920.tif"
        """{'Format': 'Gray8', 'Width': 1920, 'Height': 1920, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        resolution_test_512 = "resolution_test_512.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        simple_3d_ball = "simple_3d_ball.tif"
        """{'Format': 'Gray8', 'Width': 64, 'Height': 64, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        simple_3d_psf = "simple_3d_psf.tif"
        """{'Format': 'Gray8', 'Width': 64, 'Height': 64, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        straw_512 = "straw_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        straw_he_512 = "straw_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        sudoku = "sudoku.tiff"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        toucan = "toucan.png"
        """{'Format': 'RGB24', 'Width': 162, 'Height': 150, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        walkbridge = "walkbridge.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        water_512 = "water_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        water_he_512 = "water_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        woman_blonde = "woman_blonde.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        woman_darkhair = "woman_darkhair.tif"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        wood_grain_512 = "wood_grain_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        wood_grain_he_512 = "wood_grain_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        woolen_cloth_512 = "woolen_cloth_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        woolen_cloth_he_512 = "woolen_cloth_he_512.tiff"
        """{'Format': 'Gray8', 'Width': 512, 'Height': 512, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""

    class ImageMagik(Base, Enum):
        """ImageMagik dataset"""

        autumn_leaves = "autumn_leaves.png"
        """{'Format': 'RGB48', 'Width': 140, 'Height': 105, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        avatar = "avatar.gif"
        """{'Format': 'RGB24', 'Width': 93, 'Height': 90, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        avatar_60x60 = "avatar_60x60.png"
        """{'Format': 'RGB24', 'Width': 60, 'Height': 60, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        badge_mask = "badge_mask.png"
        """{'Format': 'Gray8', 'Width': 90, 'Height': 90, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        badge_overlay = "badge_overlay.png"
        """{'Format': 'Gray8', 'Width': 90, 'Height': 90, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        badge_shading = "badge_shading.png"
        """{'Format': 'Gray8', 'Width': 90, 'Height': 90, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bag_frame1 = "bag_frame1.gif"
        """{'Format': 'RGB24', 'Width': 97, 'Height': 92, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bag_frame2 = "bag_frame2.gif"
        """{'Format': 'RGB24', 'Width': 97, 'Height': 92, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bag_left = "bag_left.gif"
        """{'Format': 'RGB24', 'Width': 50, 'Height': 92, 'Num Frames': 11, 'FPS': 10.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bag_right = "bag_right.gif"
        """{'Format': 'RGB24', 'Width': 47, 'Height': 92, 'Num Frames': 11, 'FPS': 22.583333333333332, 'Recommended Indexer': 'bs.VideoSource'}"""
        balloon = "balloon.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bamboo = "bamboo.gif"
        """{'Format': 'RGB24', 'Width': 90, 'Height': 14, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bg = "bg.gif"
        """{'Format': 'RGB24', 'Width': 96, 'Height': 96, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        blackthin_btm = "blackthin_btm.gif"
        """{'Format': 'RGB24', 'Width': 50, 'Height': 15, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        blackthin_top = "blackthin_top.gif"
        """{'Format': 'RGB24', 'Width': 50, 'Height': 15, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bunny_anim = "bunny_anim.gif"
        """{'Format': 'RGB24', 'Width': 110, 'Height': 64, 'Num Frames': 4, 'FPS': 6.666666666666667, 'Recommended Indexer': 'bs.VideoSource'}"""
        bunny_frames = "bunny_frames.gif"
        """{'Format': 'RGB24', 'Width': 496, 'Height': 112, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        bunny_grass = "bunny_grass.gif"
        """{'Format': 'RGB24', 'Width': 120, 'Height': 80, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        castle = "castle.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colormap = "colormap.gif"
        """{'Format': 'RGB24', 'Width': 8, 'Height': 4, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colormap_332 = "colormap_332.png"
        """{'Format': 'RGB48', 'Width': 96, 'Height': 96, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colorspace_RGB = "colorspace_RGB.png"
        """{'Format': 'RGB24', 'Width': 111, 'Height': 128, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colorspace_sRGB = "colorspace_sRGB.png"
        """{'Format': 'RGB24', 'Width': 111, 'Height': 128, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colortable = "colortable.gif"
        """{'Format': 'RGB24', 'Width': 210, 'Height': 115, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        colorwheel = "colorwheel.png"
        """{'Format': 'RGB48', 'Width': 128, 'Height': 128, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        color_test = "color_test.png"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 60, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        compose_dst = "compose_dst.png"
        """{'Format': 'Gray16', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        compose_multiply = "compose_multiply.png"
        """{'Format': 'Gray16', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        compose_overlay = "compose_overlay.png"
        """{'Format': 'Gray16', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        compose_screen = "compose_screen.png"
        """{'Format': 'Gray16', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        compose_src = "compose_src.png"
        """{'Format': 'Gray16', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        cow = "cow.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        cyclops = "cyclops.png"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        cyclops_sm = "cyclops_sm.gif"
        """{'Format': 'RGB24', 'Width': 76, 'Height': 73, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dl_world_anim = "dl_world_anim.gif"
        """{'Format': 'RGB24', 'Width': 110, 'Height': 60, 'Num Frames': 6, 'FPS': 1.25, 'Recommended Indexer': 'bs.VideoSource'}"""
        dl_world_frames = "dl_world_frames.gif"
        """{'Format': 'RGB24', 'Width': 744, 'Height': 108, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dpat_hlines = "dpat_hlines.gif"
        """{'Format': 'RGB24', 'Width': 12, 'Height': 4, 'Num Frames': 9, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dpat_hlines6x4 = "dpat_hlines6x4.gif"
        """{'Format': 'RGB24', 'Width': 6, 'Height': 4, 'Num Frames': 13, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dpat_map = "dpat_map.gif"
        """{'Format': 'RGB24', 'Width': 16, 'Height': 16, 'Num Frames': 6, 'FPS': 10.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dpat_symbols = "dpat_symbols.gif"
        """{'Format': 'RGB24', 'Width': 16, 'Height': 16, 'Num Frames': 16, 'FPS': 10.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dragon_md = "dragon_md.gif"
        """{'Format': 'RGB24', 'Width': 120, 'Height': 150, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        dragon_sm = "dragon_sm.gif"
        """{'Format': 'RGB24', 'Width': 82, 'Height': 100, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        eye = "eye.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        eyeguy = "eyeguy.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        eyes = "eyes.gif"
        """{'Format': 'RGB24', 'Width': 18, 'Height': 18, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        face = "face.png"
        """{'Format': 'RGB24', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fancy_add = "fancy_add.gif"
        """{'Format': 'RGB24', 'Width': 48, 'Height': 48, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fancy_orig = "fancy_orig.gif"
        """{'Format': 'RGB24', 'Width': 48, 'Height': 48, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        fancy_sub = "fancy_sub.gif"
        """{'Format': 'RGB24', 'Width': 48, 'Height': 48, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        favicon = "favicon.ico"
        """{'Format': 'RGB24', 'Width': 16, 'Height': 16, 'Num Frames': 1, 'FPS': 90000.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        flag = "flag.gif"
        """{'Format': 'RGB24', 'Width': 8, 'Height': 11, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font = "font.gif"
        """{'Format': 'RGB24', 'Width': 320, 'Height': 128, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_0 = "font_0.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_1 = "font_1.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_2 = "font_2.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_3 = "font_3.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_4 = "font_4.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_5 = "font_5.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_6 = "font_6.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_7 = "font_7.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_8 = "font_8.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        font_9 = "font_9.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        frame = "frame.gif"
        """{'Format': 'RGB24', 'Width': 40, 'Height': 40, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        gamma_rules = "gamma_rules.png"
        """{'Format': 'RGB24', 'Width': 512, 'Height': 256, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        ghost = "ghost.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        glider_gun = "glider_gun.gif"
        """{'Format': 'RGB24', 'Width': 50, 'Height': 36, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        glitter_blue = "glitter_blue.gif"
        """{'Format': 'RGB24', 'Width': 48, 'Height': 48, 'Num Frames': 3, 'FPS': 5.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        goldthin_btm = "goldthin_btm.png"
        """{'Format': 'RGB24', 'Width': 34, 'Height': 25, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        goldthin_top = "goldthin_top.png"
        """{'Format': 'RGB24', 'Width': 34, 'Height': 25, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        grid16 = "grid16.png"
        """{'Format': 'Gray8', 'Width': 129, 'Height': 129, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        hand_point = "hand_point.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        image_error = "image_error.gif"
        """{'Format': 'RGB24', 'Width': 48, 'Height': 48, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        jigsaw_cnr = "jigsaw_cnr.png"
        """{'Format': 'Gray8', 'Width': 63, 'Height': 53, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        jigsaw_tmpl = "jigsaw_tmpl.png"
        """{'Format': 'Gray8', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        knight = "knight.png"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        koala = "koala.gif"
        """{'Format': 'RGB24', 'Width': 75, 'Height': 75, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        list_test = "list_test.gif"
        """{'Format': 'RGB24', 'Width': 96, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        logo = "logo.gif"
        """{'Format': 'RGB24', 'Width': 180, 'Height': 180, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        map_venice = "map_venice.jpg"
        """{'Format': 'YUV420P8', 'Width': 466, 'Height': 350, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        marker = "marker.png"
        """{'Format': 'RGB24', 'Width': 19, 'Height': 30, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        match_black = "match_black.gif"
        """{'Format': 'RGB24', 'Width': 64, 'Height': 77, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        match_gold = "match_gold.gif"
        """{'Format': 'RGB24', 'Width': 64, 'Height': 77, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        match_navy = "match_navy.gif"
        """{'Format': 'RGB24', 'Width': 64, 'Height': 77, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        match_white = "match_white.gif"
        """{'Format': 'RGB24', 'Width': 64, 'Height': 77, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        medical = "medical.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        midtone_image = "midtone_image.jpg"
        """{'Format': 'YUV444P8', 'Width': 160, 'Height': 233, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        moon = "moon.png"
        """{'Format': 'RGB48', 'Width': 70, 'Height': 70, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        neon_e = "neon_e.gif"
        """{'Format': 'RGB24', 'Width': 38, 'Height': 60, 'Num Frames': 2, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        neon_h = "neon_h.gif"
        """{'Format': 'RGB24', 'Width': 52, 'Height': 60, 'Num Frames': 2, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        neon_l = "neon_l.gif"
        """{'Format': 'RGB24', 'Width': 37, 'Height': 60, 'Num Frames': 2, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        neon_o = "neon_o.gif"
        """{'Format': 'RGB24', 'Width': 56, 'Height': 60, 'Num Frames': 2, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        netscape = "netscape.gif"
        """{'Format': 'RGB24', 'Width': 108, 'Height': 72, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        news = "news.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        noseguy = "noseguy.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        oak_frame_sample = "oak_frame_sample.jpg"
        """{'Format': 'YUV420P8', 'Width': 92, 'Height': 92, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        overlay_bgnd = "overlay_bgnd.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 125, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        overlay_figure = "overlay_figure.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 125, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        paddleball = "paddleball.gif"
        """{'Format': 'RGB24', 'Width': 80, 'Height': 89, 'Num Frames': 6, 'FPS': 5.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        paddleball_opt = "paddleball_opt.gif"
        """{'Format': 'RGB24', 'Width': 80, 'Height': 89, 'Num Frames': 6, 'FPS': 5.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        paint_brush = "paint_brush.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pencil = "pencil.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pencil_tile = "pencil_tile.gif"
        """{'Format': 'RGB24', 'Width': 128, 'Height': 128, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pickaxe = "pickaxe.png"
        """{'Format': 'RGB24', 'Width': 150, 'Height': 150, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        piglet = "piglet.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        plane = "plane.avi"
        """{'Format': 'RGB24', 'Width': 160, 'Height': 120, 'Num Frames': 107, 'FPS': 30.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        plasma_seeded = "plasma_seeded.jpg"
        """{'Format': 'YUV420P8', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        pokemon = "pokemon.gif"
        """{'Format': 'RGB24', 'Width': 64, 'Height': 64, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        present = "present.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        push_pin = "push_pin.png"
        """{'Format': 'RGB24', 'Width': 50, 'Height': 43, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        recycle = "recycle.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        rose = "rose.png"
        """{'Format': 'RGB24', 'Width': 70, 'Height': 46, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        rose_bg_mask = "rose_bg_mask.png"
        """{'Format': 'RGB24', 'Width': 70, 'Height': 46, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        rose_fg_mask = "rose_fg_mask.png"
        """{'Format': 'RGB24', 'Width': 70, 'Height': 46, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        rose_grey = "rose_grey.gif"
        """{'Format': 'RGB24', 'Width': 70, 'Height': 46, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        script_k = "script_k.gif"
        """{'Format': 'RGB24', 'Width': 53, 'Height': 54, 'Num Frames': 11, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        script_o = "script_o.gif"
        """{'Format': 'RGB24', 'Width': 40, 'Height': 54, 'Num Frames': 9, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        scroll = "scroll.gif"
        """{'Format': 'RGB24', 'Width': 177, 'Height': 131, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        segment = "segment.png"
        """{'Format': 'Gray8', 'Width': 150, 'Height': 150, 'Num Frames': 1, 'FPS': 30.0, 'Recommended Indexer': 'imwri.Read'}"""
        shading = "shading.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_circles = "shape_circles.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_disks = "shape_disks.gif"
        """{'Format': 'RGB24', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_figure = "shape_figure.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 125, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_lines = "shape_lines.gif"
        """{'Format': 'RGB24', 'Width': 80, 'Height': 80, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_man = "shape_man.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 125, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        shape_rectangle = "shape_rectangle.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        skull = "skull.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        smoke_skull_anim = "smoke_skull_anim.gif"
        """{'Format': 'RGB24', 'Width': 100, 'Height': 100, 'Num Frames': 12, 'FPS': 10.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        smoke_skull_frames = "smoke_skull_frames.gif"
        """{'Format': 'RGB24', 'Width': 684, 'Height': 296, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        snowman = "snowman.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        sphinx = "sphinx.gif"
        """{'Format': 'RGB24', 'Width': 66, 'Height': 56, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        splash = "splash.gif"
        """{'Format': 'RGB24', 'Width': 90, 'Height': 90, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        star = "star.gif"
        """{'Format': 'RGB24', 'Width': 52, 'Height': 52, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        storm = "storm.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        swirl_video = "swirl_video.mpg"
        """{'Format': 'YUV420P8', 'Width': 800, 'Height': 600, 'Num Frames': 130, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        terminal = "terminal.gif"
        """{'Format': 'RGB24', 'Width': 35, 'Height': 28, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        test = "test.png"
        """{'Format': 'RGB48', 'Width': 150, 'Height': 100, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        test_morphology = "test_morphology.gif"
        """{'Format': 'RGB24', 'Width': 26, 'Height': 17, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        text_scan = "text_scan.png"
        """{'Format': 'RGB48', 'Width': 383, 'Height': 224, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_aqua = "tile_aqua.jpg"
        """{'Format': 'YUV444P8', 'Width': 94, 'Height': 94, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_disks = "tile_disks.jpg"
        """{'Format': 'YUV444P8', 'Width': 94, 'Height': 94, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_fabric = "tile_fabric.gif"
        """{'Format': 'RGB24', 'Width': 94, 'Height': 94, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_rings = "tile_rings.jpg"
        """{'Format': 'YUV444P8', 'Width': 94, 'Height': 94, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_water = "tile_water.jpg"
        """{'Format': 'YUV420P8', 'Width': 128, 'Height': 128, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_weave = "tile_weave.gif"
        """{'Format': 'RGB24', 'Width': 16, 'Height': 16, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tile_wood = "tile_wood.gif"
        """{'Format': 'RGB24', 'Width': 96, 'Height': 96, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        tree = "tree.gif"
        """{'Format': 'RGB24', 'Width': 32, 'Height': 32, 'Num Frames': 1, 'FPS': 100.0, 'Recommended Indexer': 'bs.VideoSource'}"""
        wmark_image = "wmark_image.png"
        """{'Format': 'Gray8', 'Width': 122, 'Height': 94, 'Num Frames': 1, 'FPS': 25.0, 'Recommended Indexer': 'bs.VideoSource'}"""